services:
  mysql:
    image: mysql:8.0
    container_name: trucklagbe-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: trucklagbe
      MYSQL_USER: trucklagbe_user
      MYSQL_PASSWORD: trucklagbe_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_conf:/etc/mysql/conf.d
    networks:
      - trucklagbe-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local
  mysql_conf:
    driver: local

networks:
  trucklagbe-network:
    driver: bridge
